# 运行环境配置
ENV: dev # dev 开发环境; prod 生产环境;

# tcp IP和端口
TCP_IP_PORT: 0.0.0.0:21126

# http IP和端口
HTTP_SERVER_PORT: 0.0.0.0:8090

# 日志文件位置名称 info正常信息 error错误信息
LOG_PATH:
  info: ./logs/info.log
  error: ./logs/error.log

# http数据上传配置
SEND_DATA:
 status: true # true 需要http发送,false 不发送
 url: http://127.0.0.1:3000/aa

SEND_DATA_TYPE: ASCII # 数据上传格式 tcp接受到的数据以 ASCII HEX 方式发送